name: CI

on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-with-xk6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - name: Check build
        run: |
          go version
          pwd && ls -l
          
          go install go.k6.io/xk6/cmd/xk6@latest
          MODULE_NAME=$(go list -m)
          
          xk6 build \
            --output ./k6ext \
            --with $MODULE_NAME="."
          ./k6ext version

  test-go-versions:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go ${{ matrix.go-version }}
        if: matrix.go-version != 'tip'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: |
          which go
          go version
          go test -race -timeout 60s ./...
