name: k6 CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: grafana/k6-ci/.github/workflows/all.yml@4437a05286b70dbd87d6bce2bea5220694a40474 # v0.5.2
    with:
      k6-ci-ref: 4437a05286b70dbd87d6bce2bea5220694a40474 # v0.5.2
