name: Lint

on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main

permissions:
  contents: read

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
         persist-credentials: false
      - name: Codespell test
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          ignore_words_file: .codespellignore
        
