name: Lint

on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main

permissions:
  contents: read

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
         persist-credentials: false
      - name: Codespell test
        uses: codespell-project/actions-codespell@e3258cca84ce02b0bb36a3d41f2c18f719a0cc1a # v2.4.3
        with:
          ignore_words_file: .codespellignore
        
